function fig_hdl = gui_check_model
%--------------------------------------------------------------------------------
%GUI_CHECK_MODEL
%       GUI_CHECK_MODEL is the GUI screen for MODEL CHECK in Belox_GUI
%       model interactive simulator.
%
% Copyright (C) 2013 Belox Advisory Services
%
% This file is part of Belox DSGE model interactive simulator written in
% Dynare and Matlab.
%-------------------------------------------------------------------------------

% Initialize handles structure
handles = struct();

% Create all UI controls
build_gui();
movegui(handles.figure1,'center');

% Assign function output
fig_hdl = handles.figure1;

% ---------------------------------------------------------------------------
	function build_gui()
% Creation of all uicontrols

		% --- FIGURE -------------------------------------
		handles.figure1 = figure( ...
			'Tag', 'figure1', ...
			'Units', 'characters', ...
			'Position', [55.4 11.6153846153846 162 34.0769230769231], ...
			'Name', 'Belox DSGE Model Simulator - Check Model', ...
			'MenuBar', 'none', ...
			'NumberTitle', 'off', ...
			'Color', get(0,'DefaultUicontrolBackgroundColor'));

		% --- PANELS -------------------------------------
			
        handles.mainPanel = uipanel( ...
			'Parent', handles.figure1, ...
			'Tag', 'mainPanel', ...
			'UserData', zeros(1,0), ...
			'Units', 'characters', ...
			'Position', [3.2 0.307692307692308 90 30], ...
			'Title', '', ...
			'TitlePosition', 'righttop', ...
			'BorderType', 'none', ...
            'BackgroundColor', 'white');%, ...
			%'CreateFcn', @mainPanel_CreateFcn);

		handles.insidePanel = uipanel( ...
			'Parent', handles.mainPanel, ...
			'Tag', 'insidePanel', ...
			'UserData', zeros(1,0), ...
			'Units', 'characters', ...
			'Position', [0 0 90 30], ...
			'Title', '', ...
             'BackgroundColor', 'white', ...
			'BorderType', 'none');
        
        uipanel_CreateFcn();

		handles.comparisonType = uibuttongroup( ...
			'Parent', handles.figure1, ...
			'Tag', 'comparisonType', ...
			'Units', 'characters', ...
			'Position', [97.2 5.23076923076923 54.2 9.07692307692308], ...
			'Title', 'Select comparison type:', ...
			'BorderType', 'none', ...
			'BorderWidth', 0);

		% --- STATIC TEXTS -------------------------------------
		handles.text7 = uicontrol( ...
			'Parent', handles.figure1, ...
			'Tag', 'text7', ...
			'Style', 'text', ...
			'Units', 'characters', ...
			'Position', [3.2 30.3846153846154 76.8 2.30769230769231], ...
			'FontSize', 10, ...
			'FontWeight', 'bold', ...
			'String', 'Select observable variables for model check:', ...
			'HorizontalAlignment', 'left');

		handles.text8 = uicontrol( ...
			'Parent', handles.figure1, ...
			'Tag', 'text8', ...
			'Style', 'text', ...
			'Units', 'characters', ...
			'Position', [97.4 26.4615384615385 48 1.61538461538462], ...
			'String', 'The first historical observation to be displayed:', ...
			'HorizontalAlignment', 'left');

		handles.text9 = uicontrol( ...
			'Parent', handles.figure1, ...
			'Tag', 'text9', ...
			'Style', 'text', ...
			'Units', 'characters', ...
			'Position', [97.6 21.7692307692308 48 1.61538461538462], ...
			'String', 'The last historical observation to be displayed:', ...
			'HorizontalAlignment', 'left');

		% --- PUSHBUTTONS -------------------------------------
		handles.pussbuttonCheckModel = uicontrol( ...
			'Parent', handles.figure1, ...
			'Tag', 'pussbuttonCheckModel', ...
			'Style', 'pushbutton', ...
			'Units', 'characters', ...
			'Position', [94.6000000000001 1 20 2.53846153846154], ...
			'String', 'Check model !', ...
			'Callback', @pussbuttonCheckModel_Callback);

		handles.pushbuttonClose = uicontrol( ...
			'Parent', handles.figure1, ...
			'Tag', 'pushbuttonClose', ...
			'Style', 'pushbutton', ...
			'Units', 'characters', ...
			'Position', [138.8 1 20 2.53846153846154], ...
			'String', 'Close', ...
			'Callback', @pushbuttonClose_Callback);

		handles.checkboxSelectAll = uicontrol( ...
			'Parent', handles.figure1, ...
			'Tag', 'checkboxSelectAll', ...
			'Style', 'pushbutton', ...
			'Units', 'characters', ...
			'Position', [97.6 16.0769230769231 39 1.76923076923077], ...
			'String', 'Select all observable variables', ...
			'Callback', @checkboxSelectAll_Callback);

		handles.pussbuttonReset = uicontrol( ...
			'Parent', handles.figure1, ...
			'Tag', 'pussbuttonReset', ...
			'Style', 'pushbutton', ...
			'Units', 'characters', ...
			'Position', [116.600000000001 1 20 2.53846153846154], ...
			'String', 'Reset', ...
			'Callback', @pussbuttonReset_Callback);

		% --- RADIO BUTTONS -------------------------------------
	
		handles.radiobutton_UV = uicontrol( ...
			'Parent', handles.comparisonType, ...
			'Tag', 'radiobutton_UV', ...
			'Style', 'radiobutton', ...
			'Units', 'characters', ...
			'Position', [0.6 5.4 49.8 1.76923076923077], ...
			'String', 'Updated variables');
            
        handles.radiobutton_FV = uicontrol( ...
			'Parent', handles.comparisonType, ...
			'Tag', 'radiobutton_FV', ...
			'Style', 'radiobutton', ...
			'Units', 'characters', ...
			'Position', [0.6 3.8 50 1.76923076923077], ...
			'String', 'Filtered variables one step ahead');


		% --- POPUP MENU -------------------------------------
		handles.firstPeriodQuarter = uicontrol( ...
			'Parent', handles.figure1, ...
			'Tag', 'firstPeriodQuarter', ...
			'Style', 'popupmenu', ...
			'Units', 'characters', ...
			'Position', [97.4 24.7692307692308 10 1.53846153846154], ...
			'BackgroundColor', [1 1 1], ...
			'CreateFcn', @firstPeriodQuarter_CreateFcn);

		handles.firstPeriodYear = uicontrol( ...
			'Parent', handles.figure1, ...
			'Tag', 'firstPeriodYear', ...
			'Style', 'popupmenu', ...
			'Units', 'characters', ...
			'Position', [108.4 24.7692307692308 10 1.53846153846154], ...
			'BackgroundColor', [1 1 1], ...
			'CreateFcn', @firstPeriodYear_CreateFcn);

		handles.lastPeriodQuarter = uicontrol( ...
			'Parent', handles.figure1, ...
			'Tag', 'lastPeriodQuarter', ...
			'Style', 'popupmenu', ...
			'Units', 'characters', ...
			'Position', [97.6 20.0769230769231 10 1.53846153846154], ...
			'BackgroundColor', [1 1 1], ...
			'CreateFcn', @lastPeriodQuarter_CreateFcn);

		handles.lastPeriodYear = uicontrol( ...
			'Parent', handles.figure1, ...
			'Tag', 'lastPeriodYear', ...
			'Style', 'popupmenu', ...
			'Units', 'characters', ...
			'Position', [108.6 20.0769230769231 10 1.53846153846154], ...
			'BackgroundColor', [1 1 1], ...
			'CreateFcn', @lastPeriodYear_CreateFcn);


	end

% ---------------------------------------------------------------------------
	function uipanel_CreateFcn() 
       
        tabpanel = uiextras.TabPanel('Parent',  handles.mainPanel,  'Padding', 2);
        [num,txt,raw] = xlsread('Belox_GUI_modelinfo.xls','Observables','','basic');
        txt = txt(2:end,:);
        numVariables = size(txt,1);
        handles.numVariables = numVariables;
        tubNum = 0;
        numVarsOnTab = 12;
        ii=1;
        while ii <= numVariables
            if ~isempty(txt{ii,1})
                tubNum = tubNum +1;
                htabTemp = uiextras.Panel( 'Parent', tabpanel, 'Padding', 2);  % 'BorderType', 'none'
                htab(tubNum)= htabTemp;
                tempPanel(tubNum) = uipanel('Parent', htabTemp,'BackgroundColor', 'white', 'BorderType', 'none');
                position = 1;
                
                tabpanel.TabNames(tubNum) = cellstr(txt{ii,1});
                
            end
            
            rd(ii) = uicontrol('Parent', tempPanel(tubNum), 'style','checkbox',...
                'clipping','on',...
                'unit','characters',...
                'position',[3 26-(2*position) 60 2],...
                'TooltipString', txt{ii,2},...
                'string',cellstr(txt(ii,3)),...
                'BackgroundColor', 'white');
            handles.rd(ii) = rd(ii);
            position = position + 1;
            ii = ii+1;
        end
        
        %guidata(hObject,handles);  % Add the new handles structure to the figure
        
        % Show the first tab
        tabpanel.SelectedChild = 1;
	end

% ---------------------------------------------------------------------------
	function pussbuttonCheckModel_Callback(hObject,evendata) 
        first_observable_period_quarter = getappdata(0,'first_observable_period_quarter');
        
        if(variablesSelected)
            quarter1 = get(handles.firstPeriodQuarter,'Value');
            year1=  get(handles.firstPeriodYear,'Value');
            first_period = (year1-1)*4 + quarter1 - first_observable_period_quarter +1;
            
            quarter2 = get(handles.lastPeriodQuarter,'Value');
            year2=  get(handles.lastPeriodYear,'Value');
            last_period = (year2-1)*4 + quarter2 - first_observable_period_quarter +1;
            
            last_historic_period = getappdata(0,'num_historic_periods')- getappdata(0,'first_observation')+1;
            
            
            if(last_period >first_period && last_period <= last_historic_period)
                
                num=1;
                for ii = 1:handles.numVariables
                    if get(handles.rd(ii),'Value')
                        varTitle = get(handles.rd(ii),'String');
                        varName = get(handles.rd(ii),'TooltipString');
                        title_var{num} = char(varTitle);
                        i_var{num} = char(varName);
                        num=num+1;
                    end
                end
                
                comp_type = 0;
                selection =  get(handles.comparisonType, 'SelectedObject');
                if(selection == handles.radiobutton_FV)
                    comp_type = 1;
                end
                
                checkModel(title_var,i_var, first_period, last_period, comp_type);
            elseif(last_period<=first_period)
                errordlg ('The last historical observation to be displayed must be after the first historical observation.','Warning','modal')
                uicontrol(hObject)
            else(last_period >last_historic_period)
                errordlg (sprintf('The last historical observation is %s.',getappdata(0,'last_quarter_qqyyyy') ),'Warning','modal')
                uicontrol(hObject)
            end
            
        else
            errordlg ('Please select variables first!','Warning','modal')
            uicontrol(hObject)
        end
	end

    function value = variablesSelected
        value=0;
        
        for ii = 1:handles.numVariables
            if get(handles.rd(ii),'Value')
                value=1;
            end
        end
    end
% ---------------------------------------------------------------------------
	function checkboxSelectAll_Callback(hObject,evendata) 
        
        for ii = 1:handles.numVariables
            set(handles.rd(ii),'Value',1);
        end
	end

% ---------------------------------------------------------------------------
	function pussbuttonReset_Callback(hObject,evendata) 
        
        for ii = 1:handles.numVariables
            set(handles.rd(ii),'Value',0);
        end
        
        set(handles.firstPeriodQuarter,'Value',getappdata(0,'first_observable_period_quarter'));
        set(handles.firstPeriodYear,'Value',1);
        set(handles.lastPeriodQuarter,'Value',getappdata(0,'last_historic_period_quarter'));
        set(handles.lastPeriodYear,'Value',getappdata(0,'last_historic_period_year') - getappdata(0,'first_observable_period_year')+ 1);
	end


% ---------------------------------------------------------------------------
	function firstPeriodQuarter_CreateFcn(hObject,evendata) 
        set(hObject, 'String', {'Q1','Q2', 'Q3', 'Q4'});
        set(hObject,'Value',getappdata(0,'first_observable_period_quarter'));
	end

% ---------------------------------------------------------------------------
	function firstPeriodYear_CreateFcn(hObject,evendata) 
        if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
            set(hObject,'BackgroundColor','white');
        end
        
        ii=1;
        for y= getappdata(0,'first_observable_period_year'):getappdata(0,'last_historic_period_year')
            years_str{ii} = num2str(y);
            ii=ii+1;
        end
        set(hObject, 'String', years_str);
	end

% ---------------------------------------------------------------------------
    function lastPeriodQuarter_CreateFcn(hObject,evendata) 
        if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
            set(hObject,'BackgroundColor','white');
        end
        set(hObject, 'String', {'Q1','Q2', 'Q3', 'Q4'});
        set(hObject,'Value',getappdata(0,'last_historic_period_quarter'));
    end

% ---------------------------------------------------------------------------
    function lastPeriodYear_CreateFcn(hObject,evendata) 
        if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
            set(hObject,'BackgroundColor','white');
        end
        ii=1;
        
        for y= getappdata(0,'first_observable_period_year'):getappdata(0,'last_historic_period_year')
            years_str{ii} = num2str(y);
            ii=ii+1;
        end
        set(hObject, 'String', years_str);
        set(hObject,'Value',ii-1);
    end

% ---------------------------------------------------------------------------
	function pushbuttonClose_Callback(hObject,evendata) 
        close;
	end


end
