function fig_hdl = gui_set_goals
%--------------------------------------------------------------------------------
%GUI_SET_GOALS
%       GUI_SET_GOALS is the GUI screen for for seting up macroeconomic
%       goals in Belox_GUI model interactive simulator.
%
% Copyright (C) 2013 Belox Advisory Services
%
% This file is part of Belox DSGE model interactive simulator written in
% Dynare and Matlab.
%-------------------------------------------------------------------------------


% Initialize handles structure
handles = struct();

% Create all UI controls
build_gui();
movegui(handles.figureGoals,'center');

handles.setGoals = 0;

if(handles.setupNum ~=3)
     set(handles.radiobuttonAlternative, 'Visible','Off');
     set(handles.radiobuttonNew,  'position',[27.6 24 24.8 1.769]);
end
set(handles.figureGoals, 'Visible','On');

% Assign function output
fig_hdl = handles.figureGoals;

% ---------------------------------------------------------------------------
	function build_gui()
% Creation of all uicontrols

		% --- FIGURE -------------------------------------
		handles.figureGoals = figure( ...
			'Tag', 'figureGoals', ...
			'Units', 'characters', ...
			'Position', [55.4 11.6153846153846 162 34.0769230769231], ...
			'Name', 'Belox DSGE Model Simulator - Set Goals', ...
			'MenuBar', 'none', ...
			'NumberTitle', 'off', ...
            'Visible', 'off', ...
			'Color', get(0,'DefaultUicontrolBackgroundColor'));

		% --- STATIC TEXTS -------------------------------------
		handles.text8 = uicontrol( ...
			'Parent', handles.figureGoals, ...
			'Tag', 'text8', ...
			'Style', 'text', ...
			'Units', 'characters', ...
			'Position', [8.40000000000001 30.3076923076923 150 2], ...
			'FontSize', 10, ...
			'FontWeight', 'bold', ...
			'String', 'Set long-term macroeconomic goals by selecting one of the following options:', ...
			'HorizontalAlignment', 'left');

         % --- PANELS -------------------------------------
		handles.uipanelGoals = uibuttongroup( ...
			'Parent', handles.figureGoals, ...
			'Tag', 'uipanelGoals', ...
			'UserData', zeros(1,0), ...
			'Units', 'characters', ...
			'Position', [1 4.23076923076923 310 26.0769230769231], ...
			'Title', '', ...
			'BorderType', 'none', ...
			'SelectionChangeFcn', @uipanelGoals_SelectionChangeFcn);

		handles.uipanelGoalsDefinitions = uibuttongroup( ...
			'Parent', handles.uipanelGoals, ...
			'Tag', 'uipanelGoalsDefinitions', ...
			'UserData', zeros(1,0), ...
			'Units', 'characters', ...
			'Position', [0.05 0.461538461538462 157 22], ...
			'Title', 'Long term goals definitions:');

		handles.uipanelWhite = uibuttongroup( ...
			'Parent', handles.uipanelGoalsDefinitions, ...
			'Tag', 'uipanelWhite', ...
			'UserData', zeros(1,0), ...
			'Units', 'characters', ...
			'Position', [0.8 0.384615384615385 155 20.3076923076923], ...
			'BackgroundColor', [1 1 1], ...
			'Title', '', ...
			'BorderType', 'none', ...
			'CreateFcn', @uipanelWhite_CreateFcn);
        
        % --- RADIO BUTTONS -------------------------------------
		handles.radiobuttonDefault = uicontrol( ...
			'Parent', handles.uipanelGoals, ...
			'Tag', 'radiobuttonDefault', ...
			'UserData', zeros(1,0), ...
			'Style', 'radiobutton', ...
			'Units', 'characters', ...
			'Position', [5 24 20 1.76923076923077], ...
			'FontSize', 10, ...
			'String', 'Default setup');

		handles.radiobuttonAlternative = uicontrol( ...
			'Parent', handles.uipanelGoals, ...
			'Tag', 'radiobuttonAlternative', ...
			'UserData', zeros(1,0), ...
			'Style', 'radiobutton', ...
			'Units', 'characters', ...
			'Position', [27.6 24 24.8 1.76923076923077], ...
			'FontSize', 10, ...
			'String', 'Alternative setup');

		handles.radiobuttonNew = uicontrol( ...
			'Parent', handles.uipanelGoals, ...
			'Tag', 'radiobuttonNew', ...
			'UserData', zeros(1,0), ...
			'Style', 'radiobutton', ...
			'Units', 'characters', ...
			'Position', [54 24 27.6 1.76923076923077], ...
			'FontSize', 10, ...
			'String', 'New option');
        
       

		
		% --- PUSHBUTTONS -------------------------------------
		handles.pushbuttonClose = uicontrol( ...
			'Parent', handles.figureGoals, ...
			'Tag', 'pushbuttonClose', ...
			'Style', 'pushbutton', ...
			'Units', 'characters', ...
			'Position', [92.6 1.15384615384615 20 2.53846153846154], ...
			'String', 'Close', ...
			'Callback', @pushbuttonClose_Callback);

		handles.pushbuttonReset = uicontrol( ...
			'Parent', handles.figureGoals, ...
			'Tag', 'pushbuttonReset', ...
			'Style', 'pushbutton', ...
			'Units', 'characters', ...
			'Position', [69.8 1.15384615384615 20 2.53846153846154], ...
			'String', 'Reset', ...
			'Callback', @pushbuttonReset_Callback);

		handles.pussbuttonSetGoals = uicontrol( ...
			'Parent', handles.figureGoals, ...
			'Tag', 'pussbuttonSetGoals', ...
			'Style', 'pushbutton', ...
			'Units', 'characters', ...
			'Position', [47 1.15384615384615 20 2.53846153846154], ...
			'String', 'Set goals !', ...
			'Callback', @pussbuttonSetGoals_Callback);

		


	end

% ---------------------------------------------------------------------------
	function uipanelGoals_SelectionChangeFcn(hObject,evendata) 
        selection =  get(handles.uipanelGoals, 'SelectedObject');
        
        for ii=1: handles.parNum
            if(selection == handles.radiobuttonDefault)
                set(handles.parValues(ii,1), 'Enable','On');
                if(handles.setupNum ==3)
                    set(handles.parValues(ii,2), 'Enable','Off');
                end
                set(handles.parValues(ii,3), 'Enable','Off');
                set(handles.parcentageControl(ii,1), 'Enable','Off');
                set(handles.parcentageControl(ii,2), 'Enable','Off');
                set(handles.parcentageControl(ii,3), 'Enable','Off');
                set(handles.parcentageControl(ii,4), 'Enable','Off');
            elseif(selection == handles.radiobuttonAlternative && handles.setupNum==3)
                set(handles.parValues(ii,1), 'Enable','Off');
                set(handles.parValues(ii,2), 'Enable','On');
                set(handles.parValues(ii,3), 'Enable','Off');
                set(handles.parcentageControl(ii,1), 'Enable','Off');
                set(handles.parcentageControl(ii,2), 'Enable','Off');
                set(handles.parcentageControl(ii,3), 'Enable','Off');
                set(handles.parcentageControl(ii,4), 'Enable','Off');
            elseif (selection == handles.radiobuttonNew)
                set(handles.parValues(ii,1), 'Enable','Off');
                if(handles.setupNum ==3)
                    set(handles.parValues(ii,2), 'Enable','Off');
                end
                set(handles.parValues(ii,3), 'Enable','On');
                set(handles.parcentageControl(ii,1), 'Enable','On');
                set(handles.parcentageControl(ii,2), 'Enable','On');
                set(handles.parcentageControl(ii,3), 'Enable','On');
                set(handles.parcentageControl(ii,4), 'Enable','On');
            end
        end
        refresh();
	end


% ---------------------------------------------------------------------------
	function uipanelWhite_CreateFcn(hObject,evendata) 
        h = waitbar(0,'Initializing... Please wait ...', 'Name',char(getappdata(0,'model_name')));
        
        steps = 1500;
        for step = 1:steps
            
            if (step == 800)
                
                [num,txt,raw] = xlsread('Belox_GUI_modelinfo.xls','SetUpParameters','','basic');
                numParameters = size(txt,1)-1;
                txt= txt(2:end,:);
                handles.parNames =  txt(:,2);
                handles.parNum = numParameters;
                handles.setupNum = size(num,2);
                ii=1;
                position = 15;
                h_position=1;
                h_width_1 = 78;
                h_width_2 = 20;
                if( handles.setupNum ==3)
                    h_width_3 = 20;
                else
                    h_width_3 = 0;
                end
                h_width_4 = 20;
                
                textPars = uicontrol('Parent', hObject, 'style','text',...
                    'clipping','on',...
                    'String', sprintf('Parameter:'),...
                    'HorizontalAlignment','left',...
                    'FontWeight', 'Bold',...
                    'FontSize',8,...
                    'unit','characters',...
                    'position',[h_position position 15 3],...
                    'BackgroundColor', 'white');
                textBelox = uicontrol('Parent', hObject, 'style','text',...
                    'clipping','on',...
                    'String', sprintf('Default:'),...
                    'FontWeight', 'Bold',...
                    'HorizontalAlignment','left',...
                    'unit','characters',...
                    'position',[h_position + h_width_1 position 20 3],...
                    'BackgroundColor', 'white');
                
                if( handles.setupNum ==3)
                    textQuest = uicontrol('Parent', hObject, 'style','text',...
                        'clipping','on',...
                        'String', sprintf('Alternative:'),...
                        'HorizontalAlignment','left',...
                        'FontWeight', 'Bold',...
                        'unit','characters',...
                        'position',[h_position + h_width_1+h_width_2 position 20 3],...
                        'BackgroundColor', 'white');
                end
                textNew = uicontrol('Parent', hObject, 'style','text',...
                    'clipping','on',...
                    'String', sprintf('New setup:'),...
                    'FontWeight', 'Bold',...
                    'HorizontalAlignment','left',...
                    'unit','characters',...
                    'position',[h_position + h_width_1+ h_width_2+h_width_3 position 20 3],...
                    'BackgroundColor', 'white');
                
                textChange = uicontrol('Parent', hObject, 'style','text',...
                    'clipping','on',...
                    'String', 'Change (%):',...
                    'FontWeight', 'Bold',...
                    'HorizontalAlignment','left',...
                    'unit','characters',...
                    'position',[h_position+h_width_1+ h_width_2+h_width_3+h_width_4  position 15 3],...
                    'BackgroundColor', 'white');
                position = position + 2;
                
                while ii <= numParameters
                    
                    paramName(ii) = uicontrol('Parent', hObject, 'style','text',...
                        'clipping','on',...
                        'String', sprintf('%s', txt{ii,1}) ,...
                        'HorizontalAlignment','left',...
                        'unit','characters',...
                        'position',[h_position position-(3*ii) 80 1.5],...
                        'BackgroundColor', 'white');
                    
                    serbianValue(ii) = uicontrol('Parent', hObject, 'style','text',...
                        'clipping','on',...
                        'String', sprintf('%g', num(ii,1)) ,...
                        'ForegroundColor', 'Black',...
                        'HorizontalAlignment','left',...
                        'Enable', 'On',...
                        'unit','characters',...
                        'position',[h_position+h_width_1 position-(3*ii) 15 1.5],...
                        'BackgroundColor', 'white');
                    
                    if( handles.setupNum ==3)
                        questValue(ii) = uicontrol('Parent', hObject, 'style','text',...
                            'clipping','on',...
                            'String', sprintf('%g', num(ii,2)) ,...
                            'HorizontalAlignment','left',...
                            'Enable', 'Off',...
                            'BorderType', 'etchedin',...
                            'BorderWidth', '1',...
                            'unit','characters',...
                            'position',[h_position+h_width_1+h_width_2 position-(3*ii) 15 1.5],...
                            'BackgroundColor', 'white');
                    end
                    newValue(ii) = uicontrol('Parent', hObject, 'style','edit',...
                        'clipping','on',...
                        'String', sprintf('%g', num(ii,handles.setupNum)) ,...
                        'Enable', 'Off',...
                        'HorizontalAlignment','left',...
                        'unit','characters',...
                        'position',[h_position++h_width_1+h_width_2+h_width_3 position-(3*ii) 15 1.5],...
                        'BackgroundColor', 'white');
                    
                    
                    textValue(ii) = uicontrol('Parent', hObject, 'style','text',...
                        'clipping','on',...
                        'String', '0',...
                        'HorizontalAlignment','left',...
                        'Enable', 'Off',...
                        'unit','characters',...
                        'position',[h_position+h_width_1+h_width_2+h_width_3 + h_width_4+7 position-(3*ii) 6 1.5],...
                        'BackgroundColor', 'white');
                    
                    textPercent(ii) = uicontrol('Parent', hObject, 'style','text',...
                        'clipping','on',...
                        'String', '%',...
                        'HorizontalAlignment','left',...
                        'Enable', 'Off',...
                        'unit','characters',...
                        'position',[h_position+h_width_1+h_width_2+h_width_3 + h_width_4+13 position-(3*ii) 2 1.5],...
                        'BackgroundColor', 'white');
                    
                    
                    incVal(ii) = uicontrol('Parent', hObject, 'style','pushbutton',...
                        'clipping','on',...
                        'String', '+',...
                        'Enable', 'Off',...
                        'unit','characters',...
                        'position',[h_position+h_width_1+h_width_2+h_width_3 + h_width_4 position-(3*ii) 3 1.5],...
                        'Callback', {@incVal_Callback,serbianValue(ii),newValue(ii),textValue(ii)});
                    
                    decVal(ii) = uicontrol('Parent', hObject, 'style','pushbutton',...
                        'clipping','on',...
                        'String', '-',...
                        'unit','characters',...
                        'Enable', 'Off',...
                        'position',[h_position+h_width_1+h_width_2+h_width_3+h_width_4+3 position-(3*ii) 3 1.5],...
                        'Callback', {@decVal_Callback,serbianValue(ii),newValue(ii),textValue(ii)});
                    
                    set(newValue(ii), 'Callback', {@computePercentageVal_Callback,serbianValue(ii),textValue(ii)});
                    
                    %set(pars(ii), 'Callback', {@selectParameter_Callback,ii});
                    
                    handles.parValues(ii,1) = serbianValue(ii);
                    if( handles.setupNum ==3)
                        handles.parValues(ii,2) = questValue(ii);
                    end
                    handles.parValues(ii,3) = newValue(ii);
                    handles.parcentageControl(ii,1) = incVal(ii);
                    handles.parcentageControl(ii,2) = decVal(ii);
                    handles.parcentageControl(ii,3) = textValue(ii);
                    handles.parcentageControl(ii,4) = textPercent(ii);
                    
                    position = position + 1;
                    ii = ii+1;
                end
                
            end
            if (step == 1300)
                
             
                
                refresh();
            end
            waitbar(step / steps)
        end
        delete(h);
    end

% ---------------------------------------------------------------------------
    function computePercentageVal_Callback(hObject,eventdata, source, change)
        handles.policyChange = 1;
        
        source_value=str2double(get(source, 'String'));
        alternative_value = str2double(get(hObject, 'String'));
        old_value = str2double(get(change, 'String'))*source_value;
        
        change_value= round(alternative_value/source_value *100 -100);
        if(change_value > 99999)
            errordlg(sprintf('New value %g is too big.Please consider different value.',alternative_value) ,...
                sprintf('%s error', char(getappdata(0,'model_name'))),'modal');
            uicontrol(hObject);
            %set(hObject, 'String', sprintf('%g',old_value));
        end
        set(change, 'String', sprintf('%d',round(change_value)));
    end

% ---------------------------------------------------------------------------
    function incVal_Callback(hObject,eventdata, source, destination, change)
        source_value=str2double(get(source, 'String'));
        change_value=str2double(get(change, 'String'));
        change_value=change_value+1;
        
        new_Value= source_value * (1 + change_value/100);
        %new_Value= source_value +  source_value*change_value/100;
        
        set(destination, 'String', sprintf('%f',new_Value));
        set(change, 'String', sprintf('%d',change_value));
    end

% ---------------------------------------------------------------------------
    function decVal_Callback(hObject,eventdata, source, destination, change)
        source_value=str2double(get(source, 'String'));
        change_value=str2double(get(change, 'String'));
        change_value=change_value-1;
        
        new_Value= source_value * (1 + change_value/100);
        %new_Value= source_value +  source_value*change_value/100;
        
        set(destination, 'String', sprintf('%f',new_Value));
        set(change, 'String', sprintf('%d',change_value));
    end

% ---------------------------------------------------------------------------
    function pushbuttonClose_Callback(hObject,evendata)
        setappdata(0,'GoalsAreSet',handles.setGoals);
        close;
    end

% ---------------------------------------------------------------------------
	function pushbuttonReset_Callback(hObject,evendata) 
        for ii=1: handles.parNum
            set(handles.parValues(ii,3), 'String', get(handles.parValues(ii,1), 'String'));
            set(handles.parcentageControl(ii,3), 'String','0');
            
        end
        refresh();
	end

% ---------------------------------------------------------------------------
	function pussbuttonSetGoals_Callback(hObject,evendata) 
        model_name = char(getappdata(0,'model_name'));
        button = questdlg('Long term goals definition (steady state parameters) might change the model'' steady state, in which case a new mode file should be computed. Here, we use already computed mode file with settings defined under ''Default setup'' option. Do you still want to proceed?',...
            model_name, 'Yes', 'No', 'No')
        
        if(strcmp(button,'Yes')==0)
            return;
        end
        
        h = waitbar(0,'I am solving the model ... Please wait ...', 'Name',char(getappdata(0,'model_name')) );%, 'WindowStyle','modal', 'CloseRequestFcn','');
        
        steps = 1500;
        for step = 1:steps
            if step == 200
                
                selection =  get(handles.uipanelGoals, 'SelectedObject');
                
                file_core = fopen(sprintf('%s_SteadyStateParameters_core.dyn',model_name ), 'rt');
                A= fread(file_core);
                fclose(file_core);
                
                file_new = fopen(sprintf('%s_SteadyStateParameters.dyn',model_name ), 'wt');
                %         fwrite(file_new,A);
                
                fprintf(file_new, '\n\n');
                if(selection == handles.radiobuttonDefault)
                    column_index = 1;
                elseif(selection == handles.radiobuttonAlternative)
                    column_index = 2;
                elseif (selection == handles.radiobuttonNew)
                    column_index = 3;
                end
                
                
                for raw_index=1:handles.parNum
                    fprintf(file_new, sprintf('%s      =   %s; \n', handles.parNames{raw_index},get(handles.parValues(raw_index,column_index), 'String')));
                end
                fwrite(file_new,A);
                fclose(file_new);
                
            end
            
            if step == 400
                file_core = fopen(sprintf('%s_core.mod',model_name), 'rt');
                A= fread(file_core);
                fclose(file_core);
                
                file_new = fopen(sprintf('%s.mod',model_name), 'wt');
                fwrite(file_new,A);
                fprintf(file_new, '@#include "list_variables.dyn"\n');
                fprintf(file_new, sprintf('@#include "%s_Estimation_MH.dyn"\n',model_name));
                fclose(file_new);
            end
            if step == 600
                try
                    eval(sprintf('dynare %s',model_name));
                    handles.setGoals = 1;
                    msgbox('You have successfully changed long term goals definition! ',model_name);
                catch
                    errordlg(sprintf('%s DSGE model cannot find the steady state for defined long-term macroeconomic goals. Please consider different setup.',...
                        model_name),sprintf('%s error', model_name),'modal');
                    uicontrol(hObject);
                end
            end
            if step == 1200
                Belox_GUI_oo = evalin('base','oo_');
                save('Belox_GUI.mat','Belox_GUI_oo');
                
                Belox_GUI_model = evalin('base','M_');
                save('Belox_GUI.mat','Belox_GUI_model','-append');
                
            end
            waitbar(step / steps)
        end
        delete(h);
    end

end
