function gui_about(tabId)

bg_color = char(getappdata(0,'bg_color'));
special_color = char(getappdata(0,'special_color'));
top = 35;


uicontrol(tabId,'Style','text',...
    'String','About:',...
    'FontWeight', 'bold', ...
    'HorizontalAlignment', 'left','BackgroundColor', bg_color,...
    'Units','normalized','Position',[0.01 0.92 0.98 0.05] );

panel = uipanel( ...
    'Parent', tabId, ...
    'Tag', 'uipanelShocks', 'BackgroundColor', special_color,...
    'Units', 'normalized', 'Position', [0.01 0.09 0.98 0.82], ...
    'Title', '', ...
    'BorderType', 'none');

aboutStr ={'';'';'';'';'Dynare_GUI v.0.6';'';'';'Release date: March 31 2016'; '';...
    'Developed by Dynare Team and Milica Labus (milica.labus@belox.rs)';  ''; ''; '........'  };

fsize = get(0,'defaultuicontrolFontSize') + 2;
uicontrol(panel, 'style','text', 'FontSize', fsize, 'Units','normalized', ...
    'String', aboutStr, ...',...
    'Position', [0.15 0.3 0.7 0.5], 'HorizontalAlignment', 'center',  'BackgroundColor', special_color, 'enable', 'inactive');


uicontrol(tabId, 'Style','pushbutton','String','OK','Units','normalized','Position',[0.425 0.02 .15 .05],'HorizontalAlignment', 'center',  'Callback',{@close_tab,tabId} );

    function close_tab(hObject,event, hTab)
        gui_tabs.delete_tab(hTab);
        
    end
end